### PR TITLE
Fix tor controlport issue

### LINKED ISSUE #79: Issue on tor startup (seed, desktop client)
Starting a tor-enabled seed throws a tor exception.

Enabling DEBUG for `bisq.tor` in `logback.xml` :

```
13:42:00.010 INFO  [NetworkService.network-IO-pool] b.t.TorBootstrap: Tor files installed to /home/user/.local/share/bisq2_seed1/tor 
13:42:00.020 DEBUG [NetworkService.network-IO-pool] b.t.TorBootstrap: Owner pid 2931 
13:42:00.021 DEBUG [NetworkService.network-IO-pool] b.t.TorBootstrap: command for process builder: /home/user/.local/share/bisq2_seed1/tor/tor -f /home/user/.local/share/bisq2_seed1/tor/torrc __OwningControllerProcess 2931 
13:42:00.032 DEBUG [NetworkService.network-IO-pool] b.t.TorBootstrap: Process started. pid=2980 info=[user: Optional[user], cmd: /home/user/.local/share/bisq2_seed1/tor/tor, args: [-f, /home/user/.local/share/bisq2_seed1/tor/torrc, __OwningControllerProcess, 2931], startTime: Optional[2022-02-07T12:41:59.590Z], totalTime: Optional[PT0S]] 
13:42:00.036 INFO  [NetworkService.network-IO-pool] b.t.TorBootstrap: Tor process started 
13:42:00.040 DEBUG [NetworkService.network-IO-pool] b.t.TorBootstrap: Logs from control connection: >> Feb 07 13:42:00.029 [notice] Tor 0.4.5.7 (git-83f895c015de5520) running on Linux with Libevent 2.1.11-stable, OpenSSL 1.1.1j, Zlib 1.2.11, Liblzma N/A, Libzstd N/A and Glibc 2.33 as libc. 
13:42:00.044 DEBUG [NetworkService.network-IO-pool] b.t.TorBootstrap: Logs from control connection: >> Feb 07 13:42:00.029 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning 
13:42:00.045 DEBUG [NetworkService.network-IO-pool] b.t.TorBootstrap: Logs from control connection: >> Feb 07 13:42:00.029 [notice] Read configuration file "/home/user/.local/share/bisq2_seed1/tor/torrc". 
13:42:00.045 DEBUG [NetworkService.network-IO-pool] b.t.TorBootstrap: Logs from control connection: >> Feb 07 13:42:00.031 [notice] Opening Control listener on 127.0.0.1:0 
13:42:00.045 DEBUG [NetworkService.network-IO-pool] b.t.TorBootstrap: Logs from control connection: >> Feb 07 13:42:00.031 [notice] Control listener listening on port 40361. 
13:42:00.045 DEBUG [NetworkService.network-IO-pool] b.t.TorBootstrap: Logs from control connection: >> Feb 07 13:42:00.031 [notice] Opened Control listener connection (ready) on 127.0.0.1:40361 
13:42:00.046 DEBUG [NetworkService.network-IO-pool] b.t.TorBootstrap: Logs from control connection: >> Feb 07 13:42:00.031 [notice] DisableNetwork is set. Tor will not make or accept non-control network connections. Shutting down all existing connections. 
13:42:00.051 DEBUG [NetworkService.network-IO-pool] b.t.TorBootstrap: Process builder terminated 
13:42:00.051 INFO  [NetworkService.network-IO-pool] b.t.TorBootstrap: Cookie initialized 
13:42:00.054 ERROR [NetworkService.network-IO-pool] b.n.p.n.t.TorTransport: tor.startAsync failed java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:579)
	at java.base/sun.nio.ch.Net.connect(Net.java:568)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:633)
	at java.base/java.net.Socket.connect(Socket.java:583)
	at java.base/java.net.Socket.<init>(Socket.java:507)
	at java.base/java.net.Socket.<init>(Socket.java:287)
	at bisq.tor.TorController.start(TorController.java:57)
	at bisq.tor.Tor.start(Tor.java:161)
	at bisq.network.p2p.node.transport.TorTransport.initialize(TorTransport.java:51)
	at bisq.network.p2p.node.Node.maybeInitializeServer(Node.java:138)
	at bisq.network.p2p.node.NodesById.maybeInitializeServer(NodesById.java:66)
	at bisq.network.p2p.ServiceNode.maybeInitializeServer(ServiceNode.java:169)
	at bisq.network.p2p.ServiceNodesByTransport.lambda$bootstrapToNetwork$4(ServiceNodesByTransport.java:118)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

`TorBootstrap.waitForControlPort()` returns `0` as `controlPort`.

`bisq.tor.Tor.start(Tor.java:161)` then fails because `torController.start(controlPort)` uses `0` as arg.

---

Update: affects both local seeds and tor-enabled desktop clients.

### PR DESCRIPTION
**Pull request by alkum**
Update string by which the controlport is identified when initializing tor.

Fixes #79

### CODE REVIEW

File: tor/src/main/java/bisq/tor/Constants.java [hunk 1]
```diff
@@ -56,7 +56,7 @@
     public final static String TORRC_KEY_COOKIE = "CookieAuthFile";
 
     // Tor control connection
-    public final static String CONTROL_PORT_LOG_SUB_STRING = "Control collection listening on port ";
+    public final static String CONTROL_PORT_LOG_SUB_STRING = "Control listener listening on port ";
```
Comment (chimp1984) [inline tor/src/main/java/bisq/tor/Constants.java:59]: Oh that was a mistake happened when refactoring....

**Review by chimp1984 — APPROVED** [review]
utACK

File: tor/src/main/java/bisq/tor/Constants.java (hunk 1 above)
Comment (alkum) [reply tor/src/main/java/bisq/tor/Constants.java:59]: Ok that explains it :+1:
