### PR TITLE
fix: read file with fallback to allow partial config

### LINKED ISSUE #4182: Partial config is not possible using config file
Doing config as described in https://github.com/bisq-network/bisq2/pull/2201 is not possible, the app throws this error:
```
com.typesafe.config.ConfigException$ValidationFailed: /home/x/.local/share/bisq2_Bob_clear/bisq.conf: 1: application.appName: No setting at 'application.appName', expecting: string, /home/x/.local/share/bisq2_Bob_clear/bisq.conf: 1: application.network: No setting at 'application.network', expecting: object with keys [seedAddressByTransportType, supportedTransportTypes], /home/x/.local/share/bisq2_Bob_clear/bisq.conf: 1: application.devModeReputationScore: No setting at 'application.devModeReputationScore', expecting: string, /home/x/.local/share/bisq2_Bob_clear/bisq.conf: 1: application.devMode: No setting at 'application.devMode', expecting: string
	at com.typesafe.config.impl.SimpleConfig.checkValid(SimpleConfig.java:1154)
	at bisq.application.TypesafeConfigUtils.resolveCustomConfig(TypesafeConfigUtils.java:62)
	at bisq.desktop.main.content.settings.remote_control.RemoteControlController.writeCustomConfig(RemoteControlController.java:202)
	at bisq.desktop.main.content.settings.remote_control.RemoteControlController.onSavePassword(RemoteControlController.java:80)
	at bisq.desktop.main.content.settings.remote_control.RemoteControlView.lambda$onViewAttached$5(RemoteControlView.java:142)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:232)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:189)
...
```

### PR DESCRIPTION
**Pull request by wodoro**
resolves #4182 

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved configuration validation so custom config files are validated against and merged with default settings before checks, preserving user-provided values while ensuring required defaults are present for consistent application behavior.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: application/src/main/java/bisq/application/TypesafeConfigUtils.java [hunk 1]
```diff
@@ -59,7 +59,7 @@ public static Optional<Config> resolveCustomConfig(Path appDataDirPath) {
         if (Files.exists(customConfigFilePath)) {
             try {
                 com.typesafe.config.Config config = ConfigFactory.parseFile(customConfigFilePath.toFile());
-                config.checkValid(ConfigFactory.defaultReference(), "application");
+                config.withFallback(ConfigFactory.defaultReference()).checkValid(ConfigFactory.defaultReference(), "application");
```
Comment (wodoro) [inline application/src/main/java/bisq/application/TypesafeConfigUtils.java:62]: sets the fallback values only for checkValid call intentionally
